# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RotacionaFoto
                                 A QGIS plugin
 Plugin que rotaciona imagens em ângulos de 90, 180 e 270 graus.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-17
        copyright            : (C) 2021 by Jackson Oliveira/Topocart
        email                : jackend.dev@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RotacionaFoto class from file RotacionaFoto.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rotaciona_foto import RotacionaFoto
    return RotacionaFoto(iface)
